name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
env:
  QT_VERSION: '6.9.1'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
   
    steps:
      - uses: actions/checkout@v4
     
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.70
          actions-cache-folder: 'emsdk-cache'
     
      - name: Install Qt Desktop (Host)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: 'qtimageformats'
          cache: true
          add-tools-to-path: true

      - name: Install Qt WebAssembly
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'all_os'
          target: 'wasm'
          arch: 'wasm_singlethread'
          modules: 'qtimageformats'
          cache: true
          add-tools-to-path: false
     
      - name: Install CMake and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Set explicit Qt paths
        run: |
          echo "QT_HOST_PATH=/home/runner/work/QuickEdits/Qt/${{ env.QT_VERSION }}/gcc_64" >> $GITHUB_ENV
          echo "QT_WASM_PATH=/home/runner/work/QuickEdits/Qt/${{ env.QT_VERSION }}/wasm_singlethread" >> $GITHUB_ENV

      - name: Verify Qt paths
        run: |
          echo "=== QT PATHS VERIFICATION ==="
          echo "Host Qt: $QT_HOST_PATH"
          echo "WASM Qt: $QT_WASM_PATH"
          echo "Host Qt exists: $([ -d "$QT_HOST_PATH" ] && echo "YES" || echo "NO")"
          echo "WASM Qt exists: $([ -d "$QT_WASM_PATH" ] && echo "YES" || echo "NO")"
          echo "============================="
     
      - name: Build WebAssembly
        run: |
          source ${EMSDK}/emsdk_env.sh
          mkdir build
          cd build
         
          export QT_NO_PRIVATE_MODULE_WARNING=ON
         
          cmake .. \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT_CHAINLOAD_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
            -DCMAKE_TOOLCHAIN_FILE="$QT_WASM_PATH/lib/cmake/Qt6/qt.toolchain.cmake" \
            -DCMAKE_PREFIX_PATH="$QT_WASM_PATH" \
            -DCMAKE_FIND_ROOT_PATH="$QT_WASM_PATH" \
            -DQT_HOST_PATH="$QT_HOST_PATH"
          cmake --build . --parallel

      - name: Copy index.html to build directory
        run: |
          cp index.html build/ || echo "No index.html found in root"
          echo "Files in build directory:"
          ls -la build/
     
      - name: List build artifacts
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Looking for WASM files:"
          find build/ -name "*.html" -o -name "*.js" -o -name "*.wasm" | head -10
     
      - name: Setup Pages
        uses: actions/configure-pages@v4
     
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
     
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4